### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by dchigarev** [dchigarev/modin_perf_examples#1]
- [x] Add `customer_segmentation_simplified.py`
- [x] Add requirements for customer segmentation workload to `requirements.txt`
- [x] Add appendix to the article regarding hardware that was used to measure performance
- [x] Activate [gh-pages](https://dchigarev.github.io/modin_perf_examples/)
- [x] Wait for Modin's 0.28.0 release
- [x] Correct `requirements.txt`: `modin->modin[ray]`
- [x] Verify that `requirements.txt` work
- [x] Verify perf measurements on Modin 0.28.0
- [ ] Wait for a proofread from a native speaker

**Comment by YarShev** [comment]
Can this be closed?
